### ISSUE TITLE
Setup passwords for accounts

### ISSUE THREAD

**Issue by ErtonDev** [ErtonDev/add-web#14]
# Passwords will keep accounts' settings private.
Passwords aren't something crucial for the project, but if we add functions to delete accounts, then that should be protected.

First our database and API must be adapted and then `.registro` in `bot.py` has to be updated to support the input of the password but in a private way. (Probably through MD)

**Comment by ErtonDev** [comment]
Maybe we shouldn't do this. We are discussing it at the moment.

**Comment by MarcBen05** [comment]
In the end, we won't do passwords for users.
