### ISSUE TITLE
Configure and use database

### ISSUE THREAD

**Issue by ErtonDev** [ErtonDev/add-web#2]
The bot needs to start using information online so we must setup the postgreSQL db. I've deployed the db in a Heroku server and the API is working. We should "rewrite" the bot1.py files to work with the db.

**Comment by ErtonDev** [comment]
I've tested the API and I've also uploaded information to the database so take that in mind. We can delete it later though, it isn't important.

**Comment by Superjavicon** [comment]
I'm on it

**Comment by ErtonDev** [comment]
The DB is already working, now we must implement it!
