### ISSUE TITLE
There may be a bug in bot1.py line 1120

### ISSUE THREAD

**Issue by ErtonDev** [ErtonDev/add-web#4]
Line 1120 of bot1.py:

`allowed = lvl.check_license(ctx, 1)`

I think that lvl_num (1) should be 4 because of how licences are supposed to work in the game.

**Comment by xaviii03** [comment]
So change it and you will see if it works 🤷‍♂️

**Comment by ErtonDev** [comment]
oh thanks

**Comment by ErtonDev** [comment]
Fixed!
I will update the code soon...
