### ISSUE TITLE
Automatize database update process

### ISSUE THREAD

**Issue by ErtonDev** [ErtonDev/add-web#5]
# We should automatize the process of uploading the bot's information to the database
To do this we should create a script with python that does this automatically.

## Where to find the information
All the information that must be updated to the database is on the `add-web/profile/` and `add-web/bolsa/`.
*Some of the information in these files are outdated but should help to start coding the script.*

The script should be able to be executable at any time and it would update all the values of accounts and in-game values.

**You can use the `psqlapi.py` file to import useful functions from there.** These functions will allow you to connect with the database. Take into account that you will also need the environment variables for this so send me a msg as soon as you want to test the code.

## How to do it
The script should be properly written to make it easily updatable in the future. To make the `psqlapi.py` script run properly you will need to create a `.env` file in the same folder as the script (`add-web/web/`) and write on it the environmental variables used for:
```
HOST = ...
DBUSER = ...
PASS = ...
DBNAME = ...
```
### Import all the modules at the beginning of the script.
```
import psqlapi.py
```
or
```
from psqlapi.py import ...
```
In case you don't create the automation file inside of the `add-web/web/` folder and do it in `add-web/` instead:
```
import web.psqlapi.py
```
or
```
from web.psqlapi.py import ...
```
*I would recommend reading `psqlapi.py` before starting to write the automation script.*

You will also need to use the `io` module to read `.txt` files using the `open()` function.
```
import io
```
Here is an example for reading files:
``` !ad-python
file = io.open("path/to/file/file.txt", 'r')
file_lines = file.readlines()
file.close()
```
Remember to always close the file, then you can print each line of the file, here is an example:
**file.txt**
```
ABC
CBA
123
```
**Your script**
```
for i in range(3):
    print(i + 1, file_lines[i])
    # 0, 1, 2
```
**The output should look like this:**
```
1    ABC
2    CBA
3    123
```
If you have any issue with the explanation leave a comment :)

**Comment by ErtonDev** [comment]
Once this is done pls close the issue!

**Comment by Superjavicon** [comment]
Finished
